source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AYCLib_Example', :exclusive => true do
  pod 'AYCLib', :path => '../'
end

target 'AYCLib_Tests', :exclusive => true do
  pod 'AYCLib', :path => '../'

  
end
